# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  default: standard
  exclusions:
    # Exclude some linters from running on tests files.
    rules:
      - path: _test\.go
        linters:
          - errcheck
