run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    # Enabled by default linters
    # https://golangci-lint.run/usage/linters/#enabled-by-default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional linters
    - bodyclose
    - errorlint
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - misspell
    - nestif
    - prealloc
    - revive
    - typecheck
    - unconvert
    - unparam
